services:
  db:
    image: mysql:8
    container_name: fitmanage_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitmanage
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  usuarios-service:
    build: 
      context: ./usuarios-service
      dockerfile: Dockerfile
    container_name: usuarios_service
    restart: always
    env_file:
      - ./usuarios-service/.env
    ports:
      - "4001:4001"
    depends_on:
      db:
        condition: service_healthy

  afiliaciones-service:
    build: 
      context: ./afiliaciones-service
      dockerfile: Dockerfile
    container_name: afiliaciones_service
    restart: always
    env_file:
      - ./afiliaciones-service/.env
    ports:
      - "4002:4002"
    depends_on:
      db:
        condition: service_healthy

  notificaciones-service:
    build: 
      context: ./notificaciones-service
      dockerfile: Dockerfile
    container_name: notificaciones_service
    restart: always
    env_file:
      - ./notificaciones-service/.env
    ports:
      - "4005:4005"
    depends_on:
      db:
        condition: service_healthy

  consul:
    image: consul:1.15
    container_name: fitmanage_consul
    restart: always
    ports:
      - "8500:8500"
    command: consul agent -dev -client=0.0.0.0 -ui
    environment:
      - CONSUL_BIND_INTERFACE=eth0

  gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: fitmanage_gateway
    restart: always
    ports:
      - "4000:3000"
    depends_on:
      - usuarios-service
      - afiliaciones-service
      - notificaciones-service
      - asistencias-service
      - consul

  frontend1:
    build: 
      context: ./FitManageFront
      dockerfile: Dockerfile
    container_name: fitmanage_frontend1
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - gateway
    stdin_open: true
    tty: true

  asistencias-service:
    build: 
      context: ./asistencias-service
      dockerfile: Dockerfile
    container_name: asistencias_service
    restart: always
    env_file:
      - ./asistencias-service/.env
    ports:
      - "4003:4003"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
